package dns

import (
	"bufio"
	"bytes"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
)

// ResolverDir is where macOS looks for per-domain resolver files, see resolver(5)
const ResolverDir = "/etc/resolver"

const resolverMarker = "# Generated by zap"

// ResolverConfig returns the contents of a resolver file that sends lookups
// for a domain to the responder listening at addr. search_order 1 puts it
// ahead of other resolver files that claim the same domain.
func ResolverConfig(addr string) (string, error) {
	host, port, err := net.SplitHostPort(addr)
	if err != nil {
		return "", err
	}
	if ip := net.ParseIP(host); ip == nil || ip.IsUnspecified() {
		host = "127.0.0.1"
	}
	return fmt.Sprintf("%s\nnameserver %s\nport %s\nsearch_order 1\n", resolverMarker, host, port), nil
}

// IsZapResolver reports whether resolver file contents were written by zap,
// so uninstall leaves anyone else's files alone
func IsZapResolver(contents []byte) bool {
	return bytes.HasPrefix(contents, []byte(resolverMarker))
}

// ResolverConflicts returns the other files in dir that also claim one of
// the domains, keyed by domain. A file claims the domain it is named after,
// or the one in its `domain` line (eg. Apple's container tool writes
// containerization.test with `domain test`).
func ResolverConflicts(dir string, domains []string) (map[string][]string, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	conflicts := map[string][]string{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		path := filepath.Join(dir, e.Name())
		claimed, err := resolverDomain(path)
		if err != nil {
			return nil, err
		}
		for _, domain := range domains {
			if claimed == domain && e.Name() != domain {
				conflicts[domain] = append(conflicts[domain], path)
			}
		}
	}
	return conflicts, nil
}

// resolverDomain returns the domain a resolver file applies to
func resolverDomain(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 2 && fields[0] == "domain" {
			return strings.TrimSuffix(fields[1], "."), nil
		}
	}
	return filepath.Base(path), scanner.Err()
}
