package dns

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func TestResolverConfig(t *testing.T) {
	for addr, want := range map[string]string{
		"127.0.0.1:9253": "# Generated by zap\nnameserver 127.0.0.1\nport 9253\nsearch_order 1\n",
		":9253":          "# Generated by zap\nnameserver 127.0.0.1\nport 9253\nsearch_order 1\n",
		"0.0.0.0:53":     "# Generated by zap\nnameserver 127.0.0.1\nport 53\nsearch_order 1\n",
	} {
		got, err := ResolverConfig(addr)
		if err != nil {
			t.Fatal(addr, err)
		}
		if got != want {
			t.Errorf("%s: got %q, want %q", addr, got, want)
		}
		if !IsZapResolver([]byte(got)) {
			t.Errorf("%s: not recognised as a zap resolver file", addr)
		}
	}

	if _, err := ResolverConfig("9253"); err == nil {
		t.Error("expected an error for an address without a host")
	}
	if IsZapResolver([]byte("domain test\nnameserver 127.0.0.1\n")) {
		t.Error("someone else's file recognised as a zap resolver file")
	}
}

func TestResolverConflicts(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"test":                  "# Generated by zap\nnameserver 127.0.0.1\nport 9253\n",
		"containerization.test": "domain test\nsearch test\nnameserver 127.0.0.1\nport 2053\n",
		"other":                 "nameserver 127.0.0.1\n",
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0644); err != nil {
			t.Fatal(err)
		}
	}

	got, err := ResolverConflicts(dir, []string{"test", "localhost"})
	if err != nil {
		t.Fatal(err)
	}
	want := map[string][]string{"test": {filepath.Join(dir, "containerization.test")}}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}

	if got, err := ResolverConflicts(filepath.Join(dir, "missing"), []string{"test"}); err != nil || len(got) != 0 {
		t.Errorf("missing dir: got %v, %v", got, err)
	}
}
